package enums;

public enum City {
    BAKU, VIENNA, BRUSSELS, TORONTO,
    PULA, SPLIT, LARNACA, PRAGUE,
    COPANHAGEN, CAIRO, PARIS, TBILISI,
    DUSSELDORF, MUNICH, ATHENS, BUDAPEST,
    NEW_DELHI, TEL_AVIV, MILAN, ROME, TIVAT,
    AMSTERDAM, OSLO, WARSAW, BARCELONA, MADRID,
    STOCKOLM, GENEVA, ZURICH, LONDON, ISTANBUL
}
