package enums;

public enum Country {
    AZERBAIJAN, AUSTRIA, BELGIUM,
    CANADA, CROATIA, CYPRUS, CZECHIA,
    DENMARK, EGYPT, FRANCE, GEORGIA,
    GERMANY, GREECE, HUNGARY, INDIA,
    ISRAEL, ITALY, MONTENEGRO, NETHERLAND,
    NORWAY, POLAND, SPAIN, SWEDEN, SWITZERLAND,
    UK, TURKIYE
}
